### PR TITLE
Remove start scene setting

### PR DESCRIPTION
**Pull request by FejZa**
# Reality Collective - Reality Toolkit Pull Request

## Overview

We haven't been enforcing the start scene for a while now. This PR removes what's left of it from the toolkit preferences.

### CODE REVIEW

**Review by SimonDarksideJ — APPROVED** [review]

**Comment by SimonDarksideJ** [comment]
Fine to remove, so long as we do have a plan/guidance for scene management, especially since the ServiceManager "should" be in a base scene to initialise BEFORE the project starts properly.

**Comment by FejZa** [comment]
That's not true. The service manager "should" nothing. It should do whatever the developer wants it to do. If I want it to initialize only when I load a specific scene of the project, then that's when it should do it.

**Comment by FejZa** [comment]
It's really up to the developer to use the SF in a way, that fits the project. Obviously the developer has to make sure, the SF has had the time to init before trying to get services from it. But that's why we introduced those events recently.

**Comment by SimonDarksideJ** [comment]
I'd say we should provide guidance on best practices and patterns we have used in projects, especially for new developers who might not know better.

**Pull request merged**
